month_name = input("Enter month : ")
number_of_days = int(input("Enter no of days : "))
print("\n")
print("Average of " + month_name + " : ")
for i in range(number_of_days,0,-1):
    print("\n--------------------------------------------------\n")
    print(str(i) +" "+ month_name +" : "+" /10")
    print("\nCompleted Task : ")
    print("•")
    print("\nDistractions and Mistakes : ")
    print("•")
    print("\nDescribe your day :) ")
    print("•")
print("\n--------------------------------------------------\n")    
