j = input("Enter month : ")
n = int(input("Enter no of days : "))
print("\n")
print("Average of " + j + " : ")
for i in range(n,0,-1):
    print("\n--------------------------------------------------\n")
    print(str(i) +" "+ j +" : "+" /10")
    print("\nCompleted Task : ")
    print("•")
    print("\nDistractions and Mistakes : ")
    print("•")
    print("\nDescribe your day :) ")
    print("•")
print("\n--------------------------------------------------\n")    
